server:
  port: 8081
  maxHttpHeaderSize: 102400
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/boyi?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

boyi:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: Authorization
  resetPass: 888888

poi:
  repositoryBuyInDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/buyInDemo.xlsx
  repositoryBuyOutDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/buyOutDemo.xlsx
  repositoryPickMaterialDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/pickMaterialDemo.xlsx
  repositoryPickMaterialImportDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/importDemo.xlsx
  repositoryReturnMaterialDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/returnMaterialDemo.xlsx
  repositoryStockDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/stockDemo.xlsx

  orderBuyOrderDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/orderDemo.xlsx
  produceReturnShoesDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/returnShoesDemo.xlsx
  baseDataSupplierDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/baseDataSupplierDemo.xlsx
  orderProductOrderImportDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/orderProductOrderImportDemo.xlsx


picture:
  craftPath: D:/鞋业/互联网相关/ERP/boyiERPServer/target/classes/public


orderProductPrice:
  pre: D:/pre/
  real: D:/real/

