server:
  port: 8081
  maxHttpHeaderSize: 102400
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/boyi?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

boyi:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: Authorization
  resetPass: 888888
  isStartMaterialProgress: true
  toEmail: 244454526@qq.com
  csEmails: 1447647127@qq.com
  orderBeforeProductionProgress:
    sureCustomerRequired:
      sureCustomerRequiredEmail: 244454526@qq.com
      sureCustomerRequiredEmails: 244454526@qq.com
    sureShoes:
      sureShoesEmail: 1447647127@qq.com
      sureShoesEmails: 1447647127@qq.com

poi:
  repositoryBuyInDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/buyInDemo.xlsx
  repositoryBuyOutDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/buyOutDemo.xlsx
  repositoryPickMaterialDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/pickMaterialDemo.xlsx
  repositoryPickMaterialImportDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/importDemo.xlsx
  repositoryReturnMaterialDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/returnMaterialDemo.xlsx
  repositoryStockDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/stockDemo.xlsx
  repositoryInOutDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/inOutDemo.xlsx

  orderBuyOrderImportDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/orderImportDemo.xlsx
  orderBuyOrderDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/orderDemo.xlsx
  produceReturnShoesDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/returnShoesDemo.xlsx
  baseDataSupplierDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/baseDataSupplierDemo.xlsx
  orderProductOrderImportDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/orderProductOrderImportDemo.xlsx
  produceBatchImportDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/produceBatchImportDemo.xlsx
  realDosageDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/realDosageDemo.xlsx
  supplierMaterialDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/supplierMaterialDemoPath.xlsx
  baseDataMaterialDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/baseDataMaterialDemo.xlsx
  eaBaseDataMaterialDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/baseDataMaterialDemo.xlsx
  eaSupplierMaterialDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/supplierMaterialDemoPath.xlsx
  eaBaseDataSupplierDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/baseDataSupplierDemo.xlsx
  eaRepositoryBuyInDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/buyInDemo.xlsx
  eaRepositoryStockDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/stockDemo.xlsx
  eaRepositoryPickMaterialDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/pickMaterialDemo.xlsx
  eaRepositoryPickMaterialImportDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/importDemo.xlsx
  financePayShoesDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/financePayShoesDemo.xlsx
  financeFineDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/financeFineDemo.xlsx
  financeSummaryDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/financeSummaryDemo.xlsx
  shoeLastDemoPath: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/shoeLastDemo.xlsx
  financeChangeDemo: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/financeChangeDemo.xlsx
  financeTestDemo: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/financeTestDemo.xlsx
  financeTaxSupDemo: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/financeTaxSupDemo.xlsx
  financeTaxDedDemo: D:/鞋业/互联网相关/ERP/boyiERPServer/src/main/resources/excelDemo/financeTaxDedDemo.xlsx


picture:
  craftPath: D:/鞋业/互联网相关/ERP/boyiERPServer/target/classes/public
  constituentPath: D:/鞋业/互联网相关/ERP/boyiERPServer/target/classes/public
  financePayShoesPath: D:/鞋业/互联网相关/ERP/boyiERPServer/target/classes/public
  eaCraftPath: D:/鞋业/互联网相关/ERP/boyiERPServer/target/classes/public


orderProductPrice:
  pre: D:/pre/
  real: D:/real/



